### ISSUE TITLE
Definir uma classe figura

### ISSUE THREAD

**Issue by marcossantana2312** [ucsal/padroes#11]
Criar uma classe responsável pela atribuição das responsabilidades das figuras a serem criadas, de modo que, seja possível criar novas figuras sem grandes alterações no código, com base no principio OCP

**Comment by SergioMatheus** [comment]
Issue  #2 proponhe a mesma mudança

**Comment by marcossantana2312** [comment]
Acredito que a descrição está mais completa do que na Issue #2
