### ISSUE TITLE
Utilizar o padrão de Projeto Factory Method criação das Figuras 

### ISSUE THREAD

**Issue by mariojp** [ucsal/padroes#36]
Fazer essa Issue garante 2 pontos para a disciplina de OO avançado.
A implementação e a Documentação.
Documentação pode ser feita no pull request ou aqui na Issue indicando no pull request.

https://pt.wikipedia.org/wiki/Factory_Method

**Comment by danilomartinelli** [comment]
Feito o PR #39

**Comment by danilomartinelli** [comment]
Referenciando aqui o que @mariojp colocou na PR feita por mim e já mergeada:

- Retornar a Interface Figura diminui o acoplamento.
- Criar um enum com os tipos de figuras para trocar o String selecionado = "";
- Trocar os ifs por um switch

Para a task do enum, já existe uma issue aberta para isso.

**Comment by danilomartinelli** [comment]
#40 Criado para a feature:
Criar um enum com os tipos de figuras para trocar o String selecionado = "";

**Comment by KienKse** [comment]
Não só como figura como constantes para se usar na aplicação vindo de um .properties
#42
