### ISSUE TITLE
Salvar arquivo com o desenho em formato csv ou json usar o padrão Builder

### ISSUE THREAD

**Issue by mariojp** [ucsal/padroes#48]
Salvar figura em arquivo csv ou json.
Exemplo:

X | T | LARGURA | ALTURA | ESPESSURA | COR | PREENCHIMENTO |
-- | -- | -------------- | ------------ | ------------------ | ------- | ---------------------------| 
10 | 10 | 10 | 10 | 1 |  BLUE | NULL |

**Comment by cezargfilho** [comment]
Talvez a melhor forma fosse criar um objeto com os atributos necessários para escrever nos arquivos, assim tendo um "produto" gerado pelo builder. 
Usar o strategy seria outra alternativa só que mais superficial?
